version: '3' 
services:
  jetty-fileserver:
    image: openkbs/jetty-fileserver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jetty-fileserver
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
    volumes:
      - $HOME/data-docker/jetty-fileserver:/jetty_base


