version: '3' 
services:
  jetty-fileserver:
    image: openkbs/jetty-fileserver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jetty-fileserver
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - .env
    ports:
      - 18080:8080
    volumes:
      - ./jetty_base:/home/developer/jetty_base


